### ISSUE TITLE
Twic cert add error 

### ISSUE THREAD

**Issue by ranjeet0002** [kassisol/twic#1]
Hi,
I have to setup docker. For that i have to setup "HBM,TSA,TWIC" for users authentication on docker commands. I have setup TSA server, Docker host, AD.
Docker host:-
packaged installed: docker-engine-1.12.6-1.el7.centos.x86_64,hbm-0.2.2-1.el7.centos.x86_64,twic-0.1.0-1.el7.centos.x86_64,

TSA server : -

[root@workernode2 ~]# tsa info
Certificate Authority:
Type: root
Expire: 2027-05-30
Country: INDIA
State: HR
Locality: Gurgoan
Organization: Example
Organizational Unit: IT department Certificate Authority
Common Name: IT department Root CA
E-mail: admin@example.com
API:
FQDN: workernode2.example.com
Bind Address: 0.0.0.0
Bind Port: 443
Auth Type: ldap
Certificates: 1
Valid: 1
Expired: 0
Revoked: 0
Server Version: 0.1.1
Storage Driver: sqlite
Logging Driver: standard
TSA Root Dir: /var/lib/tsa

[root@workernode2 ~]# tsa auth ls
KEY VALUE
auth_type ldap
auth_host ad1.example.com
auth_port 3269
auth_tls true
auth_bind_username admin@example.com
auth_attr_members memberOf
auth_bind_password secret
auth_search_base_user ou=containers,dc=example,dc=com
auth_search_filter (&(objectCategory=containers)(cn=%s))
auth_group_admin cn=dockeradmin,ou=containers,ou=admindocker,dc=example,dc=com
auth_group_user cn=docker1,ou=containers,ou=admindocker,dc=example,dc=com

Getting error while generation twic certificate. on client node as well as docker host, below are error message.

[docker1@workernode1 ~]$ twic cert add tsa1
TSA URL : https://workernode2.example.com
Username : admin (Admin user and credential)
Password : ******
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x6b076c]

goroutine 1 [running]:
github.com/kassisol/twic/vendor/github.com/juliengk/stack/client.(*Request).Do(0xc4201a17c0, 0xa24446, 0x3, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
/go/src/github.com/kassisol/twic/vendor/github.com/juliengk/stack/client/client.go:132 +0x74c
github.com/kassisol/twic/vendor/github.com/juliengk/stack/client.(*Request).Get(0xc4201a17c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
/go/src/github.com/kassisol/twic/vendor/github.com/juliengk/stack/client/client.go:145 +0x95
github.com/kassisol/twic/vendor/github.com/kassisol/tsa/client.(*Config).GetDirectory(0xc4201ab180, 0x1f, 0xc4201ab180)
/go/src/github.com/kassisol/twic/vendor/github.com/kassisol/tsa/client/client.go:42 +0x106
github.com/kassisol/twic/cli/command/cert.runAdd(0xc420077200, 0xc42018f6d0, 0x1, 0x1)
/go/src/github.com/kassisol/twic/cli/command/cert/add.go:144 +0x60c
github.com/kassisol/twic/vendor/github.com/spf13/cobra.(*Command).execute(0xc420077200, 0xc42018f690, 0x1, 0x1, 0xc420077200, 0xc42018f690)
/go/src/github.com/kassisol/twic/vendor/github.com/spf13/cobra/command.go:648 +0x231
github.com/kassisol/twic/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc420076b40, 0xc420076b40, 0xc420076b40, 0xc420076b40)
/go/src/github.com/kassisol/twic/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/kassisol/twic/vendor/github.com/spf13/cobra.(*Command).Execute(0xc420076b40, 0xc4200001a0, 0xc4200001a0)
/go/src/github.com/kassisol/twic/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
/go/src/github.com/kassisol/twic/main.go:42 +0x2f

Please help me fix it. Thank you in advance

**Comment by ghost** [comment]
Hi,

Have you run the command `tsa server start` on workernode2? If yes, is the port 443 opened between docker1 host and workernode2?

**Comment by ranjeet0002** [comment]
Hi,
Yes, I have run above command and port 443 is opened on TSA installed server but not on client machine(workernode1)
[root@workernode2 ~]# ps -ef | grep tsa
root     130181      1  0 03:53 ?        00:00:00 /usr/sbin/tsa server start
root     130556 130515  0 07:07 pts/0    00:00:00 grep --color=auto tsa
[root@workernode2 ~]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:111             0.0.0.0:*               LISTEN      1/systemd
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      80254/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2477/master
tcp6       0      0 :::111                  :::*                    LISTEN      1/systemd
tcp6       0      0 :::22                   :::*                    LISTEN      80254/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      2477/master
tcp6       0      0 :::443                  :::*                    LISTEN      130181/tsa
udp        0      0 127.0.0.1:323           0.0.0.0:*                           80970/chronyd
udp6       0      0 ::1:323                 :::*                                80970/chronyd
[root@workernode2 ~]#

[root@workernode1 ~]# netstat -tulpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      1497/sshd
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN      2598/master
tcp6       0      0 :::22                   :::*                    LISTEN      1497/sshd
tcp6       0      0 ::1:25                  :::*                    LISTEN      2598/master
udp        0      0 127.0.0.1:323           0.0.0.0:*                           865/chronyd
udp6       0      0 ::1:323                 :::*                                865/chronyd

**Comment by ghost** [comment]
can you do a telnet from workernode1 `telnet workernode2 443` and also run `twic version`

**Comment by ranjeet0002** [comment]
[root@workernode1 ~]# twic version
TWIC 0.1.0 -- HEAD

[root@workernode1 ~]# telnet workernode2 443
Trying 192.168.254.142...
telnet: connect to address 192.168.254.142: No route to host

**Comment by ghost** [comment]
Obviously workernode1 cannot reach workernode2. 

Once that's fixed, update twic to version 0.1.1. There was some fixes done.

**Comment by ranjeet0002** [comment]
I have to update twic 0.1.1 to fix it?

**Comment by ranjeet0002** [comment]
Hi,
Lost command twic after update latest twic version.
[root@workernode1 ~]# rpm -qa | grep twic
twic-0.1.1-1.el7.centos.x86_64

[root@workernode1 ~]# twic
-bash: twic: command not found

**Comment by ghost** [comment]
that's not to fix your prob. You need to fix your network connectivity between the 2 servers first.

**Comment by ranjeet0002** [comment]
Ok, Which program will run with port 443 on client (workernode1?, firewall is stopped and selinux is disabled on both nodes.

[root@workernode1 ~]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
[root@workernode1 ~]# getenforce
Disabled

[root@workernode1 ~]# systemctl status firewalld
● firewalld.service - firewalld - dynamic firewall daemon
   Loaded: loaded (/usr/lib/systemd/system/firewalld.service; disabled; vendor preset: enabled)
   Active: inactive (dead)
[root@workernode1 ~]# getenforce
Disabled

TSA Sever
[root@workernode2 ~]# netstat -tulpn | grep tsa
tcp6       0      0 :::443                  :::*                    LISTEN      130181/tsa

But Client (workernode1)
[root@workernode1 ~]# netstat -tulpn | grep 443
tcp6       0      0 :::443                  :::*                    LISTEN      2428/httpd

**Comment by ghost** [comment]
contact me Monday on Lync

**Comment by ranjeet0002** [comment]
Please share your lync id

**Comment by ranjeet0002** [comment]
Hi,
After upgrading twic-0.1.1-1.el7.centos.x86_64, getting below error while twic add cert

[dockeradmin@workernode1 ~]$ twic cert add dockeradmin
TSA URL : https://workernode2.example.com
Username : dockeradmin
Password : **********
FATA[0061] Problem fetching directory

**Comment by ghost** [comment]
since the prob is the communication between the 2 hosts and not related to the prog, I'm closing the issue.
