### ISSUE TITLE
twic engine create issue

### ISSUE THREAD

**Issue by ranjeet0002** [kassisol/twic#2]
Hi team,
I am getting below error while create twic engine.

[root@dockermanager ~]# twic engine create
Common Name (CN) : dockermanager.example.com
Alt Names : dockermanager,192.168.254.135,127.0.0.1
TSA URL : https://workernode2.example.com
Username : dockeradmin
Password : **********
FATA[0027] Authorization denied

TSA server
[root@workernode2 ~]# tsa auth ls
KEY                    VALUE
auth_type              ldap
auth_host              ad1.example.com
auth_port              3269
auth_tls               true
auth_bind_username     dockeradmin@example.com
auth_bind_password     Comnet@123
auth_search_filter     (&(objectCategory=user)(cn=%s))
auth_attr_members      memberOf
auth_search_base_user  ou=containers,ou=admindocker,dc=example,dc=com
auth_group_admin       cn=admindocker,ou=containers,dc=example,dc=com
auth_group_user        cn=dockeradmin,ou=admindocker,dc=example,dc=com

Please help me to fix it.

**Comment by ranjeet0002** [comment]
With same user I can ssh the server but do not why getting above error.

login as: dockeradmin
dockeradmin@192.168.254.135's password:
Last login: Sun Jun 11 14:35:41 2017
[dockeradmin@dockermanager ~]$

**Comment by ghost** [comment]
still not a twic issue.
